// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrationen über eine Session-Verbindung (Supabase: Port 5432), Laufzeit über DATABASE_URL (Transaction-Pooler, Port 6543)
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
