/** Bilder im Fließtext der Blogbeiträge: nach der n-ten H2 (1-basiert). Der Seed fügt sie einmalig ein (siehe ensureBlogBodyImages). */
export type BlogBodyImage = { slug: string; afterH2: number; file: string; alt: string };

export const BLOG_BODY_IMAGES: BlogBodyImage[] = [
  { slug: "alleinfuttermittel-ergaenzungsfuttermittel", afterH2: 3, file: "alleinfuttermittel-hund-napf-ausgewogene-mahlzeit.webp", alt: "Voller Futternapf mit ausgewogener Trockenfutter-Mahlzeit, davor wartet ein Hund" },
  { slug: "alleinfuttermittel-ergaenzungsfuttermittel", afterH2: 7, file: "leckerli-ergaenzungsfutter-hund-hand.webp", alt: "Hand reicht einem Hund ein kleines Leckerli als Ergänzungsfutter" },
  { slug: "aromen-im-hundefutter-patente", afterH2: 2, file: "kroketten-fettueberzug-palatant-trockenfutter.webp", alt: "Nahaufnahme von Trockenfutter-Kroketten mit glänzendem Fettüberzug" },
  { slug: "aromen-im-hundefutter-patente", afterH2: 5, file: "hund-leerer-napf-futter-akzeptanz.webp", alt: "Zufriedener Hund sitzt vor einem leeren Napf" },
  { slug: "hundefutter-ohne-hochglanz-was-im-napf-zaehlt", afterH2: 3, file: "getreide-hundefutter-haferflocken-reis-schale.webp", alt: "Schalen mit Haferflocken und Reis als Getreide im Hundefutter" },
  { slug: "hundefutter-ohne-hochglanz-was-im-napf-zaehlt", afterH2: 4, file: "hundefutter-auswaehlen-tierarzt-beratung.webp", alt: "Tierärztin berät eine Hundehalterin in der Praxis" },
  { slug: "duerfen-hunde-popcorn-essen", afterH2: 3, file: "popcorn-pur-schale-hund-erlaubt.webp", alt: "Hund schaut auf eine Schale mit schlichtem Popcorn" },
  { slug: "duerfen-hunde-popcorn-essen", afterH2: 5, file: "ungeplatzte-popcornkoerner-gefahr-hund.webp", alt: "Gepopptes Popcorn und ungeplatzte Maiskörner auf einem Holztisch" },
  { slug: "duerfen-katzen-milch-trinken", afterH2: 3, file: "katze-trinkt-wasser-statt-milch.webp", alt: "Katze trinkt Wasser aus einem Keramiknapf" },
  { slug: "duerfen-katzen-milch-trinken", afterH2: 6, file: "katzenmilch-handel-laktosefrei-schale.webp", alt: "Katze vor einer Schale mit Milch auf dem Küchenboden" },
  { slug: "ergaenzungsfutter-katze", afterH2: 2, file: "ergaenzungsfutter-katze-snacks-auswahl.webp", alt: "Katze nimmt einen kleinen Snack als Ergänzungsfutter" },
  { slug: "ergaenzungsfutter-katze", afterH2: 5, file: "haarballen-katze-fellpflege-buerste.webp", alt: "Katze wird mit einer Bürste gekämmt gegen Haarballen" },
  { slug: "fleischanteil-hundefutter-katzenfutter", afterH2: 4, file: "frischfleisch-trockenfutter-fleischanteil.webp", alt: "Rohes Hähnchenfleisch neben einem Napf mit Trockenfutter" },
  { slug: "fleischanteil-hundefutter-katzenfutter", afterH2: 6, file: "fleischanteil-vergleichen-nassfutter-schale.webp", alt: "Schale mit Nassfutter und sichtbaren Fleischstücken" },
  { slug: "futterdeklaration-richtig-lesen", afterH2: 4, file: "zusammensetzung-hundefutter-zutaten-holzbrett.webp", alt: "Frische Zutaten wie Fleisch, Reis und Karotten auf einem Holzbrett" },
  { slug: "futterdeklaration-richtig-lesen", afterH2: 5, file: "analytische-bestandteile-futter-kuechenwaage.webp", alt: "Napf mit Trockenfutter auf einer Küchenwaage" },
  { slug: "futtermenge-hund-berechnen", afterH2: 3, file: "futtermenge-hund-napf-waage-abwiegen.webp", alt: "Futter wird für einen wartenden Hund auf der Waage abgewogen" },
  { slug: "futtermenge-hund-berechnen", afterH2: 9, file: "hund-body-condition-score-tierarzt-pruefen.webp", alt: "Tierärztin tastet die Rippen eines Hundes ab" },
  { slug: "futtermenge-katze", afterH2: 4, file: "katze-nassfutter-trockenfutter-tagesration.webp", alt: "Katze frisst Nassfutter neben einer Schale mit Trockenfutter" },
  { slug: "futtermenge-katze", afterH2: 9, file: "katze-wiegen-body-condition-score.webp", alt: "Katze wird in der Praxis gewogen" },
  { slug: "futterumstellung-hund", afterH2: 3, file: "futterumstellung-hund-altes-neues-futter-mischen.webp", alt: "Altes und neues Hundefutter werden im Napf gemischt" },
  { slug: "futterumstellung-hund", afterH2: 8, file: "hund-verweigert-neues-futter-napf.webp", alt: "Hund wendet sich vom Napf ab" },
  { slug: "futterumstellung-katze", afterH2: 4, file: "futterumstellung-katze-futter-mischen.webp", alt: "Hand mischt zwei Futtersorten im Katzennapf" },
  { slug: "futterumstellung-katze", afterH2: 6, file: "katze-frisst-neues-futter-nicht.webp", alt: "Katze sitzt skeptisch vor ihrem Napf" },
  { slug: "gelenkschmerzen-hund-produkte", afterH2: 2, file: "hund-gelenkschmerzen-tierarzt-untersuchung.webp", alt: "Tierärztin untersucht das Vorderbein eines Hundes" },
  { slug: "gelenkschmerzen-hund-produkte", afterH2: 6, file: "aelterer-hund-treppe-gelenke-bewegung.webp", alt: "Älterer Hund steigt vorsichtig eine Treppe hinunter" },
  { slug: "getreidefreies-hundefutter-sinnvoll", afterH2: 3, file: "getreidefrei-hundefutter-kartoffel-erbsen-zutaten.webp", alt: "Süßkartoffel, Erbsen und Linsen auf einem Holzbrett" },
  { slug: "getreidefreies-hundefutter-sinnvoll", afterH2: 4, file: "hund-getreide-verdauen-vollkorn-reis.webp", alt: "Hund neben Schale mit Vollkornreis und Haferflocken" },
  { slug: "hanf-fuer-hunde", afterH2: 2, file: "hanfsamen-hanfoel-hund-futtermittel.webp", alt: "Hanfsamen in einem Holzlöffel neben einer Ölflasche" },
  { slug: "hanf-fuer-hunde", afterH2: 6, file: "hund-ruhig-tierarztzimmer-cbd-forschung.webp", alt: "Ruhig liegender Hund bei der Halterin im Wartezimmer" },
  { slug: "hund-geraeuschempfindlich-alltag", afterH2: 3, file: "hund-tuerklingel-gelassen-haustuer.webp", alt: "Hund sitzt gelassen vor der Haustür" },
  { slug: "hund-maulkorb-zugfahrt-training", afterH2: 3, file: "maulkorb-training-leckerli-hund.webp", alt: "Hund bekommt beim Maulkorbtraining ein Leckerli durch den Korb" },
  { slug: "hund-ohne-garten-wochenplan", afterH2: 4, file: "hund-schlaeft-sofa-stadtwohnung-ruhezeit.webp", alt: "Hund schläft entspannt auf dem Sofa in der Stadtwohnung" },
  { slug: "hund-pfoten-reinigen-nach-regen", afterH2: 4, file: "pfotenpflege-ausstattung-handtuch-buerste-matte.webp", alt: "Mikrofaserhandtücher, Bürste und Schmutzfangmatte im Flur" },
  { slug: "seniorhund-beschaeftigung-zuhause", afterH2: 2, file: "seniorhund-becher-suchspiel-nase.webp", alt: "Alter Hund sucht ein Leckerli unter Bechern" },
  { slug: "insektenprotein-hundefutter", afterH2: 4, file: "hund-empfindlicher-magen-ruhig-decke.webp", alt: "Hund liegt ruhig auf seiner Decke neben einem Napf" },
  { slug: "insektenprotein-hundefutter", afterH2: 5, file: "nachhaltigkeit-insektenprotein-hund-natur.webp", alt: "Hund läuft über eine grüne Wiese am Waldrand" },
  { slug: "katzenfutter-richtig-auswaehlen", afterH2: 3, file: "katzenfutter-lebensphase-kitten-adult-senior.webp", alt: "Drei Katzen unterschiedlichen Alters nebeneinander" },
  { slug: "katzenfutter-richtig-auswaehlen", afterH2: 6, file: "katzenfutter-feuchtigkeit-nassfutter-napf.webp", alt: "Katze frisst Nassfutter aus einem weißen Napf" },
  { slug: "kauartikel-snacks-hund", afterH2: 2, file: "kauartikel-hund-kauknochen-auswahl.webp", alt: "Hund kaut auf einem Kauknochen" },
  { slug: "kauartikel-snacks-hund", afterH2: 6, file: "sicher-kauen-hund-aufsicht-halterin.webp", alt: "Halterin beobachtet ihren kauenden Hund" },
  { slug: "kittenfutter-wie-lange", afterH2: 3, file: "kitten-frisst-nassfutter-wachstum.webp", alt: "Kitten frisst Nassfutter aus einem kleinen Napf" },
  { slug: "kittenfutter-wie-lange", afterH2: 6, file: "junge-katze-futterwechsel-adult-futter.webp", alt: "Junge Katze neben einem Napf mit Trockenfutter" },
  { slug: "monoprotein-futter", afterH2: 2, file: "monoprotein-eine-proteinquelle-huhn.webp", alt: "Ein einzelnes Stück rohes Hähnchen auf einem Holzbrett" },
  { slug: "monoprotein-futter", afterH2: 5, file: "futtermittelallergie-hund-kratzt-ohr.webp", alt: "Hund kratzt sich am Ohr" },
  { slug: "nassfutter-oder-trockenfutter-katze", afterH2: 3, file: "katze-trinkt-trinkbrunnen-wasseraufnahme.webp", alt: "Katze trinkt aus einem Trinkbrunnen" },
  { slug: "nassfutter-oder-trockenfutter-katze", afterH2: 7, file: "mischfuetterung-katze-nass-trocken-schalen.webp", alt: "Zwei Schalen mit Nass- und Trockenfutter vor einer Katze" },
  { slug: "nassfutter-trockenfutter-haltbarkeit", afterH2: 3, file: "nassfutter-offen-kuehlschrank-abgedeckt.webp", alt: "Geöffnete Nassfutterdose mit Deckel im Kühlschrank" },
  { slug: "nassfutter-trockenfutter-haltbarkeit", afterH2: 5, file: "trockenfutter-lagerung-luftdichte-vorratsbox.webp", alt: "Luftdichte Vorratsbox für Trockenfutter mit Schaufel" },
  { slug: "natuerliche-heilmittel-hund", afterH2: 2, file: "natuerliche-heilmittel-hund-kraeuter-vorsicht.webp", alt: "Getrocknete Kräuter in kleinen Schalen" },
  { slug: "natuerliche-heilmittel-hund", afterH2: 8, file: "hund-tierarztpraxis-untersuchung-beratung.webp", alt: "Tierärztin untersucht einen Hund, Halterin daneben" },
  { slug: "obst-fuer-hunde", afterH2: 4, file: "wassermelone-hund-erlaubt-ohne-kerne.webp", alt: "Hund schnuppert an einem Stück Wassermelone" },
  { slug: "obst-fuer-hunde", afterH2: 5, file: "erdbeeren-hund-schale-nase.webp", alt: "Schale mit Erdbeeren und Hundenase" },
  { slug: "rohasche-im-futter", afterH2: 2, file: "rohasche-futter-mineralstoffe-kroketten-loeffel.webp", alt: "Kroketten auf einem Löffel in Nahaufnahme" },
  { slug: "rohasche-im-futter", afterH2: 5, file: "nassfutter-trockenfutter-vergleich-trockenmasse.webp", alt: "Nassfutter und Trockenfutter in zwei Näpfen" },
  { slug: "seniorenfutter-hund", afterH2: 2, file: "senior-hund-grauer-fang-ab-wann.webp", alt: "Älterer Hund mit grauer Schnauze im Porträt" },
  { slug: "seniorenfutter-hund", afterH2: 4, file: "seniorhund-futtermenge-gewicht-napf.webp", alt: "Halterin füttert ihren alten Hund" },
  { slug: "taurin-katze", afterH2: 3, file: "taurin-katze-herz-augen-gesundheit.webp", alt: "Aufmerksame Katze im Porträt mit klaren Augen" },
  { slug: "taurin-katze", afterH2: 5, file: "taurinreiche-zutaten-huehnerherz-fleisch.webp", alt: "Rohes Hühnerherz und Hühnerfleisch auf einem Teller" },
  { slug: "tierische-nebenerzeugnisse-gut-oder-schlecht", afterH2: 3, file: "heimtierfutter-rohstoffe-leber-herz-innereien.webp", alt: "Rohe Leber und Herz auf einem Holzbrett" },
  { slug: "tierische-nebenerzeugnisse-gut-oder-schlecht", afterH2: 5, file: "offene-deklaration-zutaten-einzeln-aufgelistet.webp", alt: "Einzelne Zutaten geordnet nebeneinander angeordnet" },
  { slug: "trockenfutter-einweichen", afterH2: 4, file: "trockenfutter-einweichen-warmes-wasser.webp", alt: "Wasser wird über Trockenfutter in einen Napf gegossen" },
  { slug: "trockenfutter-einweichen", afterH2: 6, file: "welpe-frisst-eingeweichtes-trockenfutter.webp", alt: "Welpe frisst aus einem Napf" },
  { slug: "was-duerfen-hunde-nicht-essen", afterH2: 3, file: "schokolade-hund-giftig-ausser-reichweite.webp", alt: "Hund schaut auf eine Schokoladentafel auf dem Tisch" },
  { slug: "was-duerfen-hunde-nicht-essen", afterH2: 6, file: "xylit-birkenzucker-kaugummi-hund-gefahr.webp", alt: "Kaugummi und Süßungsmittel auf einem Tisch" },
  { slug: "was-duerfen-katzen-nicht-essen", afterH2: 3, file: "zwiebeln-knoblauch-katze-giftig.webp", alt: "Zwiebeln und Knoblauch auf einem Brett, Katze im Hintergrund" },
  { slug: "was-duerfen-katzen-nicht-essen", afterH2: 8, file: "lilien-katze-giftige-pflanzen.webp", alt: "Katze neben einer Vase mit Lilien" },
  { slug: "welpenfutter-wie-lange", afterH2: 3, file: "retriever-welpe-wachstum-welpenfutter.webp", alt: "Retriever-Welpe sitzt im Gras" },
  { slug: "welpenfutter-wie-lange", afterH2: 6, file: "welpe-futtermenge-kleiner-napf-portion.webp", alt: "Welpe vor einem kleinen Napf mit Futter" },
  { slug: "wie-viele-leckerlis-am-tag", afterH2: 3, file: "leckerlis-hund-tagesration-sitz-belohnung.webp", alt: "Hund sitzt und bekommt eine Belohnung" },
  { slug: "wie-viele-leckerlis-am-tag", afterH2: 4, file: "katze-leckerli-snack-portion.webp", alt: "Katze nimmt einen kleinen Snack" },
  { slug: "zucker-im-hundefutter-katzenfutter", afterH2: 3, file: "melasse-zucker-hundefutter-zutatenliste.webp", alt: "Schale mit dunkler Melasse und Zucker" },
  { slug: "zucker-im-hundefutter-katzenfutter", afterH2: 5, file: "karamell-farbstoff-futter-kroketten.webp", alt: "Kroketten unterschiedlicher Farbe" },
];
