/** Neugierig machende Anreißer (max. 160 Zeichen) für die Vorschau-Karten der Tests. Der Seed setzt sie nur, wenn das Feld im Admin noch leer ist. */
export const REVIEW_TEASERS: Record<string, string> = {
  "belcando-adult-gf-beef": "Rind vorn, alles offen deklariert – aber rund 43 % Kohlenhydrate. Warum es trotzdem 72 Punkte schafft.",
  "bosch-hpc-adult-lamm-reis": "Günstiges Alltagsfutter mit 67 % tierischem Protein – und doch hängt vieles am Reis. Was dahintersteckt.",
  "happy-dog-naturcroq-lamm-reis-test": "Lamm im Namen, Getreide im Napf: nur 8,5 % Lamm. Warum es unter der 60-Punkte-Marke bleibt.",
  "josera-festival-im-test-76-100-punkte": "Lachs im Namen – aber nur 4 % in der Tüte. Trotzdem 76 Punkte: Was Josera Festival besser macht.",
  "royal-canin-mini-adult": "Weizenmehl an erster Stelle bei einem Premium-Namen? Was im Mini Adult wirklich steckt.",
  "tierliebhaber-nassfutter-ente-mit-reis": "91 % Ente – und trotzdem nur 60 Punkte. Die Werbung kostet diese Dose den Spitzenplatz.",
  "tierliebhaber-nassfutter-huhn-mit-gemuese": "90 % Huhn, höchster Proteinwert der Reihe – und doch gebremst. Was die Werbung verrät.",
  "tierliebhaber-nassfutter-kaninchen-mit-gemuese": "91 % Kaninchen: starkes Fleisch, aber die Werbeversprechen halten nicht, was sie sollen.",
  "tierliebhaber-nassfutter-lamm-mit-apfel": "Lamm, Apfel, Mineralstoffe – kürzer geht eine Zutatenliste kaum. Aber 80 % Wasser. Was heißt das für den Napf?",
  "tierliebhaber-nassfutter-pferd-mit-kartoffel": "94 % Pferd und trotzdem Abzug: Warum „hypoallergen“ auf der Dose zum Problem wird.",
  "tierliebhaber-nassfutter-pute-mit-reis": "91 % Pute, „ohne Gluten“ stimmt. Aber „kein Getreide“ trotz Reis? Wir haben nachgerechnet.",
  "tierliebhaber-nassfutter-rind-mit-gemuese": "Die beste Deklaration der Reihe – und dennoch nur 63 Punkte. Woran es hakt.",
  "tierliebhaber-nassfutter-ziege-mit-pastinake": "91 % Ziege, nur eine Tierart, keine Zusätze: die ehrlichste Dose der Reihe? 65 Punkte.",
  "wolfsblut-wild-duck-adult": "Ente pur, getreidefrei – aber rund 51 % Kohlenhydrate. Was Wolfsblut Wild Duck wirklich kann.",
  "animonda-carny-adult-rind-katze-nassfutter": "65 % Rind, kein Getreide, kein Zucker – und das für wenig Geld. Was dagegen spricht, lesen Sie hier.",
  "felix-so-gut-wie-es-aussieht-geschmacksvielfalt-aus-dem-wasser-im-test": "Nur 12 % Fleisch und tierische Nebenerzeugnisse – versteckt hinter Sammelbegriffen. 56 Punkte.",
  "royal-canin-indoor-katze-test": "Die „27“ im Namen stimmt. Was im Napf passiert, überrascht weniger: nur 45 Punkte.",
  "whiskas-adult-huhn-trockenfutter": "Getreide vorn, Huhn nur rund 2,8 %. Was bleibt im Napf? 38 Punkte für Whiskas 1+ Huhn.",
  "canina-petvital-gag-tabletten": "30 % Grünlippmuschel – und der GAG-Gehalt? Nicht beziffert. 58 Punkte für Canina PETVITAL.",
  "pedigree-dentastix-daily-oral-care-medium-im-test": "Zähne putzen per Snack? Getreide vorn, wenig Tierisches: das Dentastix-Konzept im Check.",
  "tierliebhaber-analdruesen-drops": "Alles offen deklariert – aber Werbung mit entzündeten Analdrüsen. Warum das Etikett allein nicht reicht.",
  "tierliebhaber-balance-kraeutersaft": "98 % Wasser und keine Kräutermengen: Was steckt wirklich im Balance Kräutersaft?",
  "tierliebhaber-bronchialsaft-hund": "Elf Kräuter, ehrliches Etikett – aber als Hustenmittel verkauft. Das geht aus unserer Sicht nicht.",
  "tierliebhaber-chillout-drops": "Vorbildlich offen – und doch als „Beruhigungsmittel“ beworben. Warum das Ärger bedeuten kann.",
  "tierliebhaber-chillout-pulver": "31 % Insektenprotein, die beste Rezeptur der Reihe – und eine Werbung, die zu weit geht.",
  "tierliebhaber-chillout-saft-hund": "98,7 % Wasser: die sauberste Deklaration der Chillout-Reihe. Aber was bringt der Saft?",
  "tierliebhaber-chillout-sticks": "Mustergültige Zusatzstoffe, aber „Arznei“ und „angstlösend“ in der Werbung. Zu viel versprochen?",
  "tierliebhaber-darmkraeuter-saft": "Ehrlicher Kräutersud mit klarer Kurdauer – aber „100 % natürlich“ trotz Zusatzstoffen? Nachgerechnet.",
  "tierliebhaber-dentalspray-hund": "Kräuterwasser für Cent-Beträge am Tag – verspricht aber mehr, als ein Futtermittel darf.",
  "tierliebhaber-g-snack": "Lange Kräuterliste, offen deklariert – doch nirgends als Ergänzungsfutter gekennzeichnet. Was fehlt?",
  "tierliebhaber-gelenk-drops": "Fast alle Wirkstoffe mit Prozent – aber Futtermittelart und Feuchte fehlen. 46 Punkte.",
  "tierliebhaber-gelenk-pulver": "Grünlippmuschel, Kollagen, Glucosamin zweistellig: die gehaltvollste Gelenk-Rezeptur im Test. 61 Punkte.",
  "tierliebhaber-gelenk-saft": "Auf dem Etikett steht Grünlippmuschel – drin ist sie nicht. Der Gelenk Saft im Check.",
  "tierliebhaber-gelenk-sticks": "Jede Zutat beziffert – und trotzdem Abzüge: Löwenzahn wird beworben, ist aber nicht enthalten.",
  "tierliebhaber-goodie-drops": "Insektenprotein, Krill, Lachsöl – offen wie selten. Warum die Goodie Drops trotzdem Punkte lassen.",
  "tierliebhaber-haehnchenbrustfilet": "Eine Zutat, 100 % Hähnchenbrust: der stärkste Kauartikel im Test. 66 Punkte.",
  "tierliebhaber-harn-und-nieren-drops": "Offene Rezeptur, aber Werbung mit Blasenentzündung und Nierensteinen. Das ist das Problem.",
  "tierliebhaber-haut-und-fell-drops": "Das transparenteste Tierliebhaber-Produkt im Test: 60 Punkte für die Haut & Fell Drops.",
  "tierliebhaber-hirschohren-mit-fell": "Eine Zutat, null Zusätze: 100 % Hirschohr. Warum es trotzdem nur 60 Punkte gibt.",
  "tierliebhaber-lammkopfhaut": "Ein schlichter Kauartikel aus einer Zutat – bis die Werbung „für Allergiker-Hunde geeignet“ verspricht.",
  "tierliebhaber-prae-probio-kur-hund": "Kräuter mit Prozent, Probiotika mit Keimzahl – doch die Proteinangaben widersprechen sich. 51 Punkte.",
  "tierliebhaber-premium-lachsoel": "100 % Lachsöl, günstig pro Tag – aber wo bleibt das Fettsäurenprofil? 55 Punkte.",
  "tierliebhaber-rinderkopfhautplatte": "100 % Rinderkopfhaut ohne Zusätze, im Mehrfachpaket günstig: solide, aber nicht perfekt. 62 Punkte.",
  "tierliebhaber-rinderohren-mit-fell": "Eine Zutat, vollständige Analyse, 65 Punkte – warum ein Kauartikel fast zum Bestwert reicht.",
  "tierliebhaber-senior-drops": "Tryptophan, Taurin, Carnitin mit Menge – aber die Feuchtigkeit fehlt. Die Senior Drops im Test.",
  "tierliebhaber-snackie-drops": "Rote Bete, Hagebutte, Spirulina, Kurkuma: offen deklariert, doch Feuchte und Energie fehlen.",
  "tierliebhaber-w-snack": "Wermut, Kürbiskern, Kokos: offen deklariert – aber ein Versprechen über Monate ohne Beleg.",
  "tierliebhaber-z-pulver": "Kräftig gewürzt und offen deklariert – verspricht aber Schutz vor „Plagegeistern“. Ist das zulässig?",
  "tierliebhaber-z-snack": "Gut deklarierte Kugeln mit Insektenprotein und Krill – doch die Aufmachung wirft Fragen auf. 53 Punkte.",
  "tierliebhaber-zahnfee-pulver": "Kräuterpulver für frischen Atem – aber 175,60 € je kg. Lohnt sich das?",
  "tierliebhaber-zahnfee-sticks": "Kräuter mit Prozent, Zink mit Kennnummer – doch Feuchte und Energie fehlen. 57 Punkte.",
  "tierliebhaber-zahnpflege-granulat": "Sauber deklariert – aber „entzündungshemmendes“ Kurkuma geht nach unserer Einschätzung zu weit.",
  "dreamies-mit-huhn": "Katzen lieben sie – aber Getreide steht vorn und Huhn macht nur 4 % aus. Die Wahrheit über Dreamies.",
  "gimcat-malt-soft-paste-extra": "Im Kern Malz und Fett: ehrlich deklariert, aber was bringt die Paste wirklich? 55 Punkte.",
  "tierliebhaber-dentalspray-katzen": "Kräuterwasser für wenige Cent am Tag – verspricht Hilfe bei Zahnfleischproblemen. Darf es das?",
  "tierliebhaber-prae-probio-kur-katze": "Gute Präbiotika und zwei Bakterienstämme – doch die Werbung spricht von Giardien und Würmern. 40 Punkte.",
};
